-- Project      : SkiMap
-- Description  : Un site web permettant de vérifier les station de ski Suisse.
-- File         : 05-data.sql
-- Authors      : Jérémy Ballanfat
-- Date         : 2 Février 2024